### ISSUE TITLE
Momo does not recover when loosing the db connection

### ISSUE THREAD

**Issue by klassm** [TNG/momo-scheduler#382]
Possible solution: Increase the number of attempts to reconnect to the db (do you actually ever want to stop?)
See [Mongo Docs: connection-settings/](https://mongodb.github.io/node-mongodb-native/2.2/reference/connecting/connection-settings/)

Probably increase reconnectTries to something very very high.

**Comment by YaniKolev** [comment]
I think the linked documentation is somewhat outdated. It looks like those reconnection options are no longer [supported](https://mongodb.github.io/node-mongodb-native/3.6/reference/unified-topology/).
