### ISSUE TITLE
Handle multi instances properly

### ISSUE THREAD

**Issue by klassm** [TNG/momo-scheduler#461]
When running multiple instances, it would be great if Momo would ensure only one of those instances schedules any jobs.

Current implementation: All instances will simultaneously try to schedule all jobs (they have all timers started internally). That's a huge amount of overhead and leads to quite a high probability of race conditions, so scheduling jobs multiple times where you actually wanted to run it only once. There's two checks to prevent this currently - one in the Scheduler and one in the Repository. What I am proposing is solving this in a way that all instances are not even trying it, but only _one_ master instance.

How could this work:
- Some instances start simultaneously.
- Each of them starts a timer to check for the one active scheduler.
- This check happens by looking in the database looking for a record containing the active instance. This record contains a schedulerId and a timestamp.
- If they find such a record and the timestamp is smaller than a given timeout interval, they do nothing except of checking again in some seconds.
- If they don't find such a record, they set themselves as active (at best atomic, otherwise something like double checked locking?) and schedule all jobs
- While being active, the active record needs to be updated every few seconds, so other schedulers won't consider themselves as active
- If the active scheduler finds itself not being active anymore, it cleans up. This usually won't happen, as the instance will be dead then.

Benefit:
- Only one instance is active ever. So no race conditions.
- Less overhead, as only once instance is keeping all the timers.
- Easier to understand, as the whole scheduling code is meant to be executed only once at the same time. There is one global check to see whether you are active or not.

What do you think?

**Comment by NiklasEi** [comment]
I agree that this should be the default behaviour.
Executions already have something similar with a `scheduleId`/`timestamp` and a timeout mechanic. I have to refresh my understanding there, but we might be able to use those already existing fields for the functionality you describe.
