### ISSUE TITLE
Momo generates a lot of Mongo Errors

### ISSUE THREAD

**Issue by YaniKolev** [TNG/momo-scheduler#624]
Looks like we expect and gracefully handle a Mongo error here: https://github.com/TNG/momo-scheduler/blob/main/src/repository/SchedulesRepository.ts#L57

However, this spams the logs of any responsible DB with errors like `MongoServerError: E11000 duplicate key error collection:(...)`.

There are expected at this place and we do handle them correctly but the behaviour can make people think there's something wrong with the service. 

We should investigate if there's a different way to perform this check

**Comment by YaniKolev** [comment]
If we decide to solve the issue via transactions, we should make it clear what Mongo version we require. I think they might be a v5 version.

**Comment by weissu42** [comment]
Look like transactions are available since Mongo 4.2: https://www.mongodb.com/docs/v5.0/core/transactions/

**Comment by weissu42** [comment]
MongoSchedule#isActiveSchedule() seems to be unused and should be removed
