### ISSUE TITLE
Allow undefined errors in executeHandler

### ISSUE THREAD

**Issue by schnuri-schnuri** [TNG/momo-scheduler#720]
The [catch](https://github.com/TNG/momo-scheduler/blob/main/src/executor/JobExecutor.ts#L76) of the try-catch in the `JobExecutor`'s `executeHandler` espects an error with a message.

If a handler rejects with undefined (`return Promis.reject()`) this leads to a TypeError which could prevent further jobs to be executed.

Instead of
`      result = { status: ExecutionStatus.failed, handlerResult: (e as Error).message };`
one could write
`      result = { status: ExecutionStatus.failed, handlerResult: (e as Error)?.message };`
or something similar. I can open a PR to change this.

**Comment by YaniKolev** [comment]
Good catch (pun very much intended 😄 )! 

Consult the [CONTRIBUTING](https://github.com/TNG/momo-scheduler/blob/main/CONTRIBUTING.md) guidelines and open a PR!

**Comment by YaniKolev** [comment]
Fixed in 2.1.0
